const SUCCESS_STATUS_CODE = 200;
const CREATION_SUCCESS_STATUS_CODE = 201;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_STATUS_CODE = 401;
const NOT_FOUND_STATUS_CODE = 404;

module.exports = { SUCCESS_STATUS_CODE, CREATION_SUCCESS_STATUS_CODE, INTERNAL_SERVER_ERROR_STATUS_CODE, BAD_REQUEST_STATUS_CODE, UNAUTHORIZED_STATUS_CODE, NOT_FOUND_STATUS_CODE }